### ISSUE TITLE
GraphQl ....banan thik koren  :)

### ISSUE THREAD

**Issue by Muntasir-Mahmud** [iamtakdir/iamtakdir#1]

**Comment by iamtakdir** [comment]
thanks for the reply,  I will change it soon

**Comment by iamtakdir** [comment]
@Muntasir-Mahmud  Spelling to thik e ace Brother !! can you recheck it :3 ami change kori nai akno

**Comment by Muntasir-Mahmud** [comment]
@iamtakdir GraphQL or graphql would be more appropriate I think

**Comment by iamtakdir** [comment]
:3 Akeh this must be an Uppercase, Lowercase issue, Btw thanks, Man.
